name: Test Pip Install Code

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:       # See https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master for choices
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install package
        run: pip install cartorio

      - name: Test package
        run: python tests/from_pip.py